name: work_camera_app
description: 工作记录 — 多场景分组拍照工具
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.3
  uuid: ^4.2.0
  intl: ^0.19.0
  image: ^4.1.0
  permission_handler: ^11.1.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
